config:
  first-line-h1: false
  no-inline-html:
    allowed_elements:
      - div
      - img
  line-length:
    line_length: 80
    code_blocks: true
    tables: false
  no-duplicate-heading:
    siblings_only: true
  blanks-around-fences:
    list_items: false
overrides:
  - filter:
      - CHANGELOG.md
    config:
      line-length: false
    combine: merge
