import { mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

interface ModeAnchors {
  bg: string;
  bgAlt: string;
  fg: string;
  muted: string;
  subtle: string;
  border: string;
  warn: string;
  alert: string;
  ink: string;
}

interface ColorSchema {
  schemaVersion: number;
  modes: Record<'dark' | 'light', ModeAnchors>;
  presets: Array<{ name: string; dark: string; light: string }>;
  namedBackgrounds: Array<{ name: string; seed: string }>;
  resolution: {
    luma: {
      red: number;
      green: number;
      blue: number;
      divisor: number;
      lightThreshold: number;
    };
    surfaceMix: { bg: number; panel: number; bgAlt: number; border: number };
    textMix: Record<'dark' | 'light', { muted: number; subtle: number }>;
    baseAltMix: number;
  };
}

const website = resolve(import.meta.dir, '..');
const plugin = resolve(website, '..', 'chroma.tmux');
const outputDir = resolve(website, '.generated');

const process = Bun.spawn([plugin, '--dump-colors'], {
  stdout: 'pipe',
  stderr: 'inherit',
});
const text = await new Response(process.stdout).text();
if (await process.exited !== 0) {
  throw new Error('chroma.tmux --dump-colors failed');
}

const colors = JSON.parse(text) as ColorSchema;
if (colors.schemaVersion !== 1 || colors.presets.length === 0) {
  throw new Error('unsupported or empty Chroma color schema');
}

const first = colors.presets[0];
if (!first) {
  throw new Error('Chroma color schema has no presets');
}

function mix(firstColor: string, secondColor: string, percent: number): string {
  return '#' + [1, 3, 5].map((index) => {
    const firstChannel = parseInt(firstColor.slice(index, index + 2), 16);
    const secondChannel = parseInt(secondColor.slice(index, index + 2), 16);
    const value = Math.floor(
      (firstChannel * percent + secondChannel * (100 - percent)) / 100
    );
    return value.toString(16).padStart(2, '0');
  }).join('');
}

function cssMode(mode: 'dark' | 'light'): string {
  const anchors = colors.modes[mode];
  const accent = first[mode];
  const selector = mode === 'dark' ? ':root' : ":root[data-theme='light']";
  const autoAccents = ['blue', 'green', 'yellow', 'red'].map((name) => {
    const preset = colors.presets.find((entry) => entry.name === name);
    if (!preset) throw new Error(`missing auto-swatch preset: ${name}`);
    return preset[mode];
  });
  return `${selector} {
  --bar: ${anchors.bg};
  --panel-raised: ${anchors.bgAlt};
  --text: ${anchors.fg};
  --muted: ${anchors.muted};
  --subtle: ${anchors.subtle};
  --warn: ${anchors.warn};
  --alert: ${anchors.alert};
  --ink: ${anchors.ink};
  --accent: ${accent};
  --accent-alt: ${mix(accent, anchors.bg, colors.resolution.baseAltMix)};
  --auto-accent-1: ${autoAccents[0]};
  --auto-accent-2: ${autoAccents[1]};
  --auto-accent-3: ${autoAccents[2]};
  --auto-accent-4: ${autoAccents[3]};
}`;
}

const moduleSource = `// Generated by scripts/generate-colors.ts. Do not edit.
export const colorSchema = ${JSON.stringify(colors, null, 2)} as const;
`;
const css = `${cssMode('dark')}\n\n${cssMode('light')}\n`;
const prepaintColors = {
  modes: colors.modes,
  namedBackgrounds: colors.namedBackgrounds,
  resolution: {
    luma: colors.resolution.luma,
    surfaceMix: colors.resolution.surfaceMix,
    textMix: colors.resolution.textMix,
  },
};
const prepaint = `// Generated by scripts/generate-colors.ts. Do not edit.
(function () {
  var colors = ${JSON.stringify(prepaintColors)};
  var read = function (key) {
    try {
      return localStorage.getItem(key);
    } catch (error) {
      return null;
    }
  };
  var stored = read('chroma-background');
  var forced = read('chroma-mode');
  if (forced !== 'dark' && forced !== 'light') forced = null;
  var root = document.documentElement;
  if (stored === 'light' || stored === 'dark') {
    root.dataset.theme = forced || stored;
    return;
  }
  var named = {};
  colors.namedBackgrounds.forEach(function (entry) {
    named[entry.name] = entry.seed;
  });
  if (Object.prototype.hasOwnProperty.call(named, stored || '')) {
    stored = named[stored];
  }
  if (!/^#[0-9a-f]{6}$/.test(stored || '')) {
    root.dataset.theme = forced || 'dark';
    return;
  }
  var seed = [1, 3, 5].map(function (offset) {
    return parseInt(stored.slice(offset, offset + 2), 16);
  });
  var lumaSpec = colors.resolution.luma;
  var luma = Math.floor(
    (lumaSpec.red * seed[0] + lumaSpec.green * seed[1] +
      lumaSpec.blue * seed[2]) / lumaSpec.divisor
  );
  var mode = forced ||
    (luma >= lumaSpec.lightThreshold ? 'light' : 'dark');
  var fgHex = colors.modes[mode].fg;
  var fg = [1, 3, 5].map(function (offset) {
    return parseInt(fgHex.slice(offset, offset + 2), 16);
  });
  var mix = function (percent) {
    return '#' + seed.map(function (channel, index) {
      var value = Math.floor(
        (fg[index] * percent + channel * (100 - percent)) / 100
      );
      return value.toString(16).padStart(2, '0');
    }).join('');
  };
  var surface = colors.resolution.surfaceMix;
  var text = colors.resolution.textMix[mode];
  root.dataset.theme = mode;
  root.style.setProperty('--canvas', stored);
  root.style.setProperty('--bar', mix(surface.bg));
  root.style.setProperty('--panel', mix(surface.panel));
  root.style.setProperty('--panel-raised', mix(surface.bgAlt));
  root.style.setProperty('--line', mix(surface.border));
  root.style.setProperty('--muted', mix(text.muted));
  root.style.setProperty('--subtle', mix(text.subtle));
})();
`;
const siteModule = `// Generated by scripts/generate-colors.ts. Do not edit.
export const colorCss = ${JSON.stringify(css)};
export const prepaint = ${JSON.stringify(prepaint)};
`;

async function write(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await Bun.write(path, contents);
}

await Promise.all([
  write(resolve(outputDir, 'colors.ts'), moduleSource),
  write(resolve(outputDir, 'colors.css'), css),
  write(resolve(outputDir, 'prepaint.js'), prepaint),
  write(resolve(outputDir, 'site.ts'), siteModule),
]);
